# Site settings
name: 健康八十岁
email: jk80.service@gmail.com
author: 李鹏
url: https://www.jk80.com.cn
baseurl: ""
description: 病人为中心，不是病为中心
meta_description: 健康八十岁;个人博客
motto: 生命不能重来，健康需要管理
banner: 病人为中心，不是病为中心

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

highlighter: Pygments

# Build settings
markdown: kramdown

google_analytics: UA-100074327-1
#baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

FB:
  comments :
    provider : disqus
    disqus :
        short_name : jk80